//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.17929.
// 
#pragma warning disable 1591

namespace OMS_NEW.gis_reference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback _1Get_CompanyOperationCompleted;
        
        private System.Threading.SendOrPostCallback _2Get_Circle_listOperationCompleted;
        
        private System.Threading.SendOrPostCallback _3Get_Circle_detailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback _4Get_Division_listOperationCompleted;
        
        private System.Threading.SendOrPostCallback _5Get_Division_detailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback _6Get_Sub_Division_listOperationCompleted;
        
        private System.Threading.SendOrPostCallback _7Get_Sub_Division_detailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback _8Get_Complaint_Centre_listOperationCompleted;
        
        private System.Threading.SendOrPostCallback _9Get_Complaint_Centre_detailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback _Substation_Div_detailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback _CA_Dt_detailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback _Dt_CA_listOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::OMS_NEW.Properties.Settings.Default.OMS_NEW_gis_reference_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event _1Get_CompanyCompletedEventHandler _1Get_CompanyCompleted;
        
        /// <remarks/>
        public event _2Get_Circle_listCompletedEventHandler _2Get_Circle_listCompleted;
        
        /// <remarks/>
        public event _3Get_Circle_detailsCompletedEventHandler _3Get_Circle_detailsCompleted;
        
        /// <remarks/>
        public event _4Get_Division_listCompletedEventHandler _4Get_Division_listCompleted;
        
        /// <remarks/>
        public event _5Get_Division_detailsCompletedEventHandler _5Get_Division_detailsCompleted;
        
        /// <remarks/>
        public event _6Get_Sub_Division_listCompletedEventHandler _6Get_Sub_Division_listCompleted;
        
        /// <remarks/>
        public event _7Get_Sub_Division_detailsCompletedEventHandler _7Get_Sub_Division_detailsCompleted;
        
        /// <remarks/>
        public event _8Get_Complaint_Centre_listCompletedEventHandler _8Get_Complaint_Centre_listCompleted;
        
        /// <remarks/>
        public event _9Get_Complaint_Centre_detailsCompletedEventHandler _9Get_Complaint_Centre_detailsCompleted;
        
        /// <remarks/>
        public event _Substation_Div_detailsCompletedEventHandler _Substation_Div_detailsCompleted;
        
        /// <remarks/>
        public event _CA_Dt_detailsCompletedEventHandler _CA_Dt_detailsCompleted;
        
        /// <remarks/>
        public event _Dt_CA_listCompletedEventHandler _Dt_CA_listCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/_1Get_Company", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet _1Get_Company() {
            object[] results = this.Invoke("_1Get_Company", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void _1Get_CompanyAsync() {
            this._1Get_CompanyAsync(null);
        }
        
        /// <remarks/>
        public void _1Get_CompanyAsync(object userState) {
            if ((this._1Get_CompanyOperationCompleted == null)) {
                this._1Get_CompanyOperationCompleted = new System.Threading.SendOrPostCallback(this.On_1Get_CompanyOperationCompleted);
            }
            this.InvokeAsync("_1Get_Company", new object[0], this._1Get_CompanyOperationCompleted, userState);
        }
        
        private void On_1Get_CompanyOperationCompleted(object arg) {
            if ((this._1Get_CompanyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._1Get_CompanyCompleted(this, new _1Get_CompanyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/_2Get_Circle_list", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet _2Get_Circle_list(string company) {
            object[] results = this.Invoke("_2Get_Circle_list", new object[] {
                        company});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void _2Get_Circle_listAsync(string company) {
            this._2Get_Circle_listAsync(company, null);
        }
        
        /// <remarks/>
        public void _2Get_Circle_listAsync(string company, object userState) {
            if ((this._2Get_Circle_listOperationCompleted == null)) {
                this._2Get_Circle_listOperationCompleted = new System.Threading.SendOrPostCallback(this.On_2Get_Circle_listOperationCompleted);
            }
            this.InvokeAsync("_2Get_Circle_list", new object[] {
                        company}, this._2Get_Circle_listOperationCompleted, userState);
        }
        
        private void On_2Get_Circle_listOperationCompleted(object arg) {
            if ((this._2Get_Circle_listCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._2Get_Circle_listCompleted(this, new _2Get_Circle_listCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/_3Get_Circle_details", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet _3Get_Circle_details(string circle) {
            object[] results = this.Invoke("_3Get_Circle_details", new object[] {
                        circle});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void _3Get_Circle_detailsAsync(string circle) {
            this._3Get_Circle_detailsAsync(circle, null);
        }
        
        /// <remarks/>
        public void _3Get_Circle_detailsAsync(string circle, object userState) {
            if ((this._3Get_Circle_detailsOperationCompleted == null)) {
                this._3Get_Circle_detailsOperationCompleted = new System.Threading.SendOrPostCallback(this.On_3Get_Circle_detailsOperationCompleted);
            }
            this.InvokeAsync("_3Get_Circle_details", new object[] {
                        circle}, this._3Get_Circle_detailsOperationCompleted, userState);
        }
        
        private void On_3Get_Circle_detailsOperationCompleted(object arg) {
            if ((this._3Get_Circle_detailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._3Get_Circle_detailsCompleted(this, new _3Get_Circle_detailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/_4Get_Division_list", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet _4Get_Division_list(string circle) {
            object[] results = this.Invoke("_4Get_Division_list", new object[] {
                        circle});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void _4Get_Division_listAsync(string circle) {
            this._4Get_Division_listAsync(circle, null);
        }
        
        /// <remarks/>
        public void _4Get_Division_listAsync(string circle, object userState) {
            if ((this._4Get_Division_listOperationCompleted == null)) {
                this._4Get_Division_listOperationCompleted = new System.Threading.SendOrPostCallback(this.On_4Get_Division_listOperationCompleted);
            }
            this.InvokeAsync("_4Get_Division_list", new object[] {
                        circle}, this._4Get_Division_listOperationCompleted, userState);
        }
        
        private void On_4Get_Division_listOperationCompleted(object arg) {
            if ((this._4Get_Division_listCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._4Get_Division_listCompleted(this, new _4Get_Division_listCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/_5Get_Division_details", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet _5Get_Division_details(string division_code, string division_name) {
            object[] results = this.Invoke("_5Get_Division_details", new object[] {
                        division_code,
                        division_name});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void _5Get_Division_detailsAsync(string division_code, string division_name) {
            this._5Get_Division_detailsAsync(division_code, division_name, null);
        }
        
        /// <remarks/>
        public void _5Get_Division_detailsAsync(string division_code, string division_name, object userState) {
            if ((this._5Get_Division_detailsOperationCompleted == null)) {
                this._5Get_Division_detailsOperationCompleted = new System.Threading.SendOrPostCallback(this.On_5Get_Division_detailsOperationCompleted);
            }
            this.InvokeAsync("_5Get_Division_details", new object[] {
                        division_code,
                        division_name}, this._5Get_Division_detailsOperationCompleted, userState);
        }
        
        private void On_5Get_Division_detailsOperationCompleted(object arg) {
            if ((this._5Get_Division_detailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._5Get_Division_detailsCompleted(this, new _5Get_Division_detailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/_6Get_Sub_Division_list", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet _6Get_Sub_Division_list(string division_code, string division_name) {
            object[] results = this.Invoke("_6Get_Sub_Division_list", new object[] {
                        division_code,
                        division_name});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void _6Get_Sub_Division_listAsync(string division_code, string division_name) {
            this._6Get_Sub_Division_listAsync(division_code, division_name, null);
        }
        
        /// <remarks/>
        public void _6Get_Sub_Division_listAsync(string division_code, string division_name, object userState) {
            if ((this._6Get_Sub_Division_listOperationCompleted == null)) {
                this._6Get_Sub_Division_listOperationCompleted = new System.Threading.SendOrPostCallback(this.On_6Get_Sub_Division_listOperationCompleted);
            }
            this.InvokeAsync("_6Get_Sub_Division_list", new object[] {
                        division_code,
                        division_name}, this._6Get_Sub_Division_listOperationCompleted, userState);
        }
        
        private void On_6Get_Sub_Division_listOperationCompleted(object arg) {
            if ((this._6Get_Sub_Division_listCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._6Get_Sub_Division_listCompleted(this, new _6Get_Sub_Division_listCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/_7Get_Sub_Division_details", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet _7Get_Sub_Division_details(string subdivision_code, string subdivision_name) {
            object[] results = this.Invoke("_7Get_Sub_Division_details", new object[] {
                        subdivision_code,
                        subdivision_name});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void _7Get_Sub_Division_detailsAsync(string subdivision_code, string subdivision_name) {
            this._7Get_Sub_Division_detailsAsync(subdivision_code, subdivision_name, null);
        }
        
        /// <remarks/>
        public void _7Get_Sub_Division_detailsAsync(string subdivision_code, string subdivision_name, object userState) {
            if ((this._7Get_Sub_Division_detailsOperationCompleted == null)) {
                this._7Get_Sub_Division_detailsOperationCompleted = new System.Threading.SendOrPostCallback(this.On_7Get_Sub_Division_detailsOperationCompleted);
            }
            this.InvokeAsync("_7Get_Sub_Division_details", new object[] {
                        subdivision_code,
                        subdivision_name}, this._7Get_Sub_Division_detailsOperationCompleted, userState);
        }
        
        private void On_7Get_Sub_Division_detailsOperationCompleted(object arg) {
            if ((this._7Get_Sub_Division_detailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._7Get_Sub_Division_detailsCompleted(this, new _7Get_Sub_Division_detailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/_8Get_Complaint_Centre_list", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet _8Get_Complaint_Centre_list(string subdivision_code, string subdivision_name) {
            object[] results = this.Invoke("_8Get_Complaint_Centre_list", new object[] {
                        subdivision_code,
                        subdivision_name});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void _8Get_Complaint_Centre_listAsync(string subdivision_code, string subdivision_name) {
            this._8Get_Complaint_Centre_listAsync(subdivision_code, subdivision_name, null);
        }
        
        /// <remarks/>
        public void _8Get_Complaint_Centre_listAsync(string subdivision_code, string subdivision_name, object userState) {
            if ((this._8Get_Complaint_Centre_listOperationCompleted == null)) {
                this._8Get_Complaint_Centre_listOperationCompleted = new System.Threading.SendOrPostCallback(this.On_8Get_Complaint_Centre_listOperationCompleted);
            }
            this.InvokeAsync("_8Get_Complaint_Centre_list", new object[] {
                        subdivision_code,
                        subdivision_name}, this._8Get_Complaint_Centre_listOperationCompleted, userState);
        }
        
        private void On_8Get_Complaint_Centre_listOperationCompleted(object arg) {
            if ((this._8Get_Complaint_Centre_listCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._8Get_Complaint_Centre_listCompleted(this, new _8Get_Complaint_Centre_listCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/_9Get_Complaint_Centre_details", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet _9Get_Complaint_Centre_details(string complaint_center_code, string complaint_center_name) {
            object[] results = this.Invoke("_9Get_Complaint_Centre_details", new object[] {
                        complaint_center_code,
                        complaint_center_name});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void _9Get_Complaint_Centre_detailsAsync(string complaint_center_code, string complaint_center_name) {
            this._9Get_Complaint_Centre_detailsAsync(complaint_center_code, complaint_center_name, null);
        }
        
        /// <remarks/>
        public void _9Get_Complaint_Centre_detailsAsync(string complaint_center_code, string complaint_center_name, object userState) {
            if ((this._9Get_Complaint_Centre_detailsOperationCompleted == null)) {
                this._9Get_Complaint_Centre_detailsOperationCompleted = new System.Threading.SendOrPostCallback(this.On_9Get_Complaint_Centre_detailsOperationCompleted);
            }
            this.InvokeAsync("_9Get_Complaint_Centre_details", new object[] {
                        complaint_center_code,
                        complaint_center_name}, this._9Get_Complaint_Centre_detailsOperationCompleted, userState);
        }
        
        private void On_9Get_Complaint_Centre_detailsOperationCompleted(object arg) {
            if ((this._9Get_Complaint_Centre_detailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._9Get_Complaint_Centre_detailsCompleted(this, new _9Get_Complaint_Centre_detailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/_Substation_Div_details", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet _Substation_Div_details(string substation_code) {
            object[] results = this.Invoke("_Substation_Div_details", new object[] {
                        substation_code});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void _Substation_Div_detailsAsync(string substation_code) {
            this._Substation_Div_detailsAsync(substation_code, null);
        }
        
        /// <remarks/>
        public void _Substation_Div_detailsAsync(string substation_code, object userState) {
            if ((this._Substation_Div_detailsOperationCompleted == null)) {
                this._Substation_Div_detailsOperationCompleted = new System.Threading.SendOrPostCallback(this.On_Substation_Div_detailsOperationCompleted);
            }
            this.InvokeAsync("_Substation_Div_details", new object[] {
                        substation_code}, this._Substation_Div_detailsOperationCompleted, userState);
        }
        
        private void On_Substation_Div_detailsOperationCompleted(object arg) {
            if ((this._Substation_Div_detailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._Substation_Div_detailsCompleted(this, new _Substation_Div_detailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/_CA_Dt_details", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet _CA_Dt_details(string ca) {
            object[] results = this.Invoke("_CA_Dt_details", new object[] {
                        ca});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void _CA_Dt_detailsAsync(string ca) {
            this._CA_Dt_detailsAsync(ca, null);
        }
        
        /// <remarks/>
        public void _CA_Dt_detailsAsync(string ca, object userState) {
            if ((this._CA_Dt_detailsOperationCompleted == null)) {
                this._CA_Dt_detailsOperationCompleted = new System.Threading.SendOrPostCallback(this.On_CA_Dt_detailsOperationCompleted);
            }
            this.InvokeAsync("_CA_Dt_details", new object[] {
                        ca}, this._CA_Dt_detailsOperationCompleted, userState);
        }
        
        private void On_CA_Dt_detailsOperationCompleted(object arg) {
            if ((this._CA_Dt_detailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._CA_Dt_detailsCompleted(this, new _CA_Dt_detailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/_Dt_CA_list", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet _Dt_CA_list(string DT_Code) {
            object[] results = this.Invoke("_Dt_CA_list", new object[] {
                        DT_Code});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void _Dt_CA_listAsync(string DT_Code) {
            this._Dt_CA_listAsync(DT_Code, null);
        }
        
        /// <remarks/>
        public void _Dt_CA_listAsync(string DT_Code, object userState) {
            if ((this._Dt_CA_listOperationCompleted == null)) {
                this._Dt_CA_listOperationCompleted = new System.Threading.SendOrPostCallback(this.On_Dt_CA_listOperationCompleted);
            }
            this.InvokeAsync("_Dt_CA_list", new object[] {
                        DT_Code}, this._Dt_CA_listOperationCompleted, userState);
        }
        
        private void On_Dt_CA_listOperationCompleted(object arg) {
            if ((this._Dt_CA_listCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._Dt_CA_listCompleted(this, new _Dt_CA_listCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void _1Get_CompanyCompletedEventHandler(object sender, _1Get_CompanyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _1Get_CompanyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _1Get_CompanyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void _2Get_Circle_listCompletedEventHandler(object sender, _2Get_Circle_listCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _2Get_Circle_listCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _2Get_Circle_listCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void _3Get_Circle_detailsCompletedEventHandler(object sender, _3Get_Circle_detailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _3Get_Circle_detailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _3Get_Circle_detailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void _4Get_Division_listCompletedEventHandler(object sender, _4Get_Division_listCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _4Get_Division_listCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _4Get_Division_listCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void _5Get_Division_detailsCompletedEventHandler(object sender, _5Get_Division_detailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _5Get_Division_detailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _5Get_Division_detailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void _6Get_Sub_Division_listCompletedEventHandler(object sender, _6Get_Sub_Division_listCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _6Get_Sub_Division_listCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _6Get_Sub_Division_listCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void _7Get_Sub_Division_detailsCompletedEventHandler(object sender, _7Get_Sub_Division_detailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _7Get_Sub_Division_detailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _7Get_Sub_Division_detailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void _8Get_Complaint_Centre_listCompletedEventHandler(object sender, _8Get_Complaint_Centre_listCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _8Get_Complaint_Centre_listCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _8Get_Complaint_Centre_listCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void _9Get_Complaint_Centre_detailsCompletedEventHandler(object sender, _9Get_Complaint_Centre_detailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _9Get_Complaint_Centre_detailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _9Get_Complaint_Centre_detailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void _Substation_Div_detailsCompletedEventHandler(object sender, _Substation_Div_detailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _Substation_Div_detailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _Substation_Div_detailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void _CA_Dt_detailsCompletedEventHandler(object sender, _CA_Dt_detailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _CA_Dt_detailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _CA_Dt_detailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void _Dt_CA_listCompletedEventHandler(object sender, _Dt_CA_listCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _Dt_CA_listCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _Dt_CA_listCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591